name: Loading Data Automation

on:
  schedule:
    # daily
    - cron: "0 8 * * *"
  # support manual trigger
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: load data
        with: # Set the secret as an input
          super_secret: ${{.streamlit/service_account_key.json}}
        run: |
          python update_table_construction_incremental.py