name: Update table automatically

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update_table:
    runs-on: ubuntu-latest

    steps:
    - name: Check directory structure
      run: |
        echo "Contents of current directory:"
        ls -ls
        echo "Contents of repository root:"
        find . -type f -name "*.py" | sort

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Update table
      env:
        super_secret: ${{ secrets.WILL_NAGA_KRISHNA_SECRETS }}
      run: python update_table_construction_incremental.py



# jobs:
#   update_table:
#     runs-on: ubuntu-latest
# #     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"
#           cache: pip
#       - name: Install dependencies
#         run: pip install -r requirements.txt
#       - name: load data
        # env: # Set the secret as an input
        #   super_secret: ${{ secrets.WILL_NAGA_KRISHNA_SECRETS }}
        # run: |
        #   python update_table_construction_incremental.py "$super_secret"